
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//font awesome icons libraries
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Layout from "./components/Layout";
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "nextui",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Layout >
                    {children}
                </Layout>

            </body>
        </html>
    );
}
